### ISSUE TITLE
JSON errors starting up V2.2.3

### ISSUE THREAD

**Issue by Andy2No** [christofmuc/KnobKraft-orm#337] opened 2024-09-29 09:18 UTC
I realise V2.2.3 is now out of date, but I was trying to stick with it so I can use my usual PC for this purpose, which has Windows 7.

Today, when I start it up, I just get a stream of JSON errors in the log.  Is there a cure for this problem?  I can't find any mention of it:

```
10:13:01: info Launching KnobKraft Orm
10:13:01: Overriding built-in automatic category rules with file C:\Users\andy\AppData\Roaming\KnobKraft\automatic_categories.jsonc
10:13:01: Overriding built-in import category rules with file C:\Users\andy\AppData\Roaming\KnobKraft\mapping_categories.jsonc
10:13:01: warning Overriding built-in adaptation DSI Tetr4 (found in user directory C:\Users\andy\KnobKraft-Adaptations)
10:13:01: warning Overriding built-in adaptation Minilogue XD* (found in user directory C:\Users\andy\KnobKraft-Adaptations)
10:13:01: warning Overriding built-in adaptation Minilogue XD (found in user directory C:\Users\andy\KnobKraft-Adaptations)
10:13:01: warning Overriding built-in adaptation Pro 800 (found in user directory C:\Users\andy\KnobKraft-Adaptations)
10:13:01: warning Overriding built-in adaptation Waldorf Pulse 2 (found in user directory C:\Users\andy\KnobKraft-Adaptations)
10:13:02: warning Lost communication with DSI Prophet Rev2 on channel 1 of device  - please rerun auto-detect synths!
10:13:02: warning Lost communication with DSI Tetr4 on channel 1 of device  - please rerun auto-detect synths!
10:13:02: warning Lost communication with Waldorf Blofeld on channel 1 of device MIDISPORT 4x4 Out C - please rerun auto-detect synths!
10:13:03: warning Lost communication with ZOOM MS Series on channel 1 of device ZOOM MS Series - please rerun auto-detect synths!
10:13:03: error JSON error parsing source information of patch: [json.exception.parse_error.101] parse error at line 1, column 2: syntax error while parsing value - invalid literal; last read: 'n<U+0000>'
10:13:03: error JSON error parsing source information of patch: [json.exception.parse_error.101] parse error at line 1, column 78: syntax error while parsing value - invalid string: ill-formed UTF-8 byte; last read: '"'
10:13:03: error JSON error parsing source information of patch: [json.exception.parse_error.101] parse error at line 1, column 78: syntax error while parsing value - invalid string: ill-formed UTF-8 byte; last read: '" '
10:13:03: error JSON error parsing source information of patch: [json.exception.parse_error.101] parse error at line 1, column 78: syntax error while parsing value - invalid string: ill-formed UTF-8 byte; la
```

I was trying to make an adaptation for the Reface CS, based on the one for the CP.  I've now removed that .py file from the KnobKraft-Adaptations folder though and still get the same stream of error messages, so presumably that's not the cause.

**Comment by Andy2No** [comment] 2024-09-29 09:27
After removing the two .jsonc files it refers to above, I still get the same or similar errors:

```
10:25:00: info Launching KnobKraft Orm
10:25:00: warning Overriding built-in adaptation DSI Tetr4 (found in user directory C:\Users\andy\KnobKraft-Adaptations)
10:25:00: warning Overriding built-in adaptation Minilogue XD* (found in user directory C:\Users\andy\KnobKraft-Adaptations)
10:25:00: warning Overriding built-in adaptation Minilogue XD (found in user directory C:\Users\andy\KnobKraft-Adaptations)
10:25:00: warning Overriding built-in adaptation Pro 800 (found in user directory C:\Users\andy\KnobKraft-Adaptations)
10:25:00: warning Overriding built-in adaptation Waldorf Pulse 2 (found in user directory C:\Users\andy\KnobKraft-Adaptations)
10:25:00: warning Lost communication with DSI Prophet Rev2 on channel 1 of device  - please rerun auto-detect synths!
10:25:01: warning Lost communication with DSI Tetr4 on channel 1 of device  - please rerun auto-detect synths!
10:25:01: warning Lost communication with Waldorf Blofeld on channel 1 of device MIDISPORT 4x4 Out C - please rerun auto-detect synths!
10:25:01: warning Lost communication with ZOOM MS Series on channel 1 of device ZOOM MS Series - please rerun auto-detect synths!
10:25:01: error JSON error parsing source information of patch: [json.exception.parse_error.101] parse error at line 1, column 2: syntax error while parsing value - invalid literal; last read: 'n<U+0000>'
10:25:01: error JSON error parsing source information of patch: [json.exception.parse_error.101] parse error at line 1, column 78: syntax error while parsing value - invalid string: ill-formed UTF-8 byte; last read: '"'
10:25:01: error JSON error parsing source information of patch: [json.exception.parse_error.101] parse error at line 1, column 78: syntax error while parsing value - invalid string: ill-formed UTF-8 byte; last read: '" '
10:25:01: error JSON error parsing source information of patch: [json.exception.parse_error.101] parse error at line 1, column 78: syntax error while parsing value - invalid string: ill-formed UTF-8 byte; last read: '"'
10:25:01: error JSON error parsing source information of patch: [json.exception.parse_error.101] parse error at line 1, column 2: syntax error while parsing value - invalid literal; last read: 'n<U+0000>'
10:25:01: error JSON error parsing source information of patch: [json.exception.parse_error.101] parse error at line 1, column 2: syntax error while parsing value - invalid literal; last read: 't<U+0000>'
...
```

**Comment by Andy2No** [comment] 2024-09-29 10:21
How can I tell what files it's trying to parse, while producing these json errors? It says, for example, "parse error at line 1, column 2:" but doesn't give any indication of the file that it's line 1 of.

**Comment by Andy2No** [comment] 2024-09-29 10:53
Solution (hopefully):  I've removed mapping_categories.jsonc from the folder where my database gets opened from (within My Documents, not at the default location).  It was dated 2022-01-04, but as far as I'm aware, has never caused this problem before.

I'm now back to a normal looking error log, without the mysterious json errors.

Feel free to close this.  Maybe it will be useful to someone else, I don't know.  Perhaps the problem was very version specific?  Or maybe it relates to updating after  putting the database in a non-default location, and will affect other people.  I hadn't used V2.2.3 much but I expect I would have seen the error if it happened before.

I think it would be a good idea to at least make this error message give a clue what file is involved though.

I'll get back to what I was trying to do when I recover the energy.

**Comment by christofmuc** [comment] 2024-09-29 14:35
Sorry to hear that made trouble, I agree there needs to be a better error message. That import mapping seems to be a bit of a forgotten feature! I will make sure newer KnobKrafts behave better!

**Comment by Andy2No** [comment] 2024-09-29 15:03
Thanks.

**Comment by christofmuc** [comment] 2024-11-02 18:39
@Andy2No I looked at this, and strangely the error is not produced by the code reading the mapping_categories.jsonc file, but by code that reads the "source information" string from the database. This is a complex json document that includes all detail information on the import (it is displayed in the properties section of the current patch). It is complex because it could say "Bulk import" but also remember the exact file from the bulk import for this patch. 

As these json structs are created by the Orm only, there is no manual interaction normally possible that could produce this errors. This is weird.

**Comment by Andy2No** [comment] 2024-11-03 12:11
I think that particular file was produced while I was trying to understand how to use the category mapping option (which I still don't, but never mind).  It would have been done using the Orm, but definitely by an older version.  The odd part, to me, is that the file didn't cause those errors before v2.2.3.

**Comment by christofmuc** [comment] 2024-11-04 22:25
Hm, ok. I was pointing out that the error you reported was about import information in the database not being in the correct, but that doesn't seem to stick. I'll close this ticket as the problem is gone and regarding an old version as well, feel free to open again in case it happens again!

**Closed by christofmuc** 2024-11-04 22:25 UTC
Labels: bug, need more information
