### ISSUE TITLE
naming of (backup) files and its handling

### ISSUE THREAD

**Issue by markusschloesser** [christofmuc/KnobKraft-orm#94] opened 2021-05-18 19:31 UTC
![image](https://user-images.githubusercontent.com/59286549/118711165-8f251080-b81f-11eb-9d20-4d4a9f867145.png)
while trying to find a missing patch, I noticed that kk had seemingly opened lots of backup db files and produced a lot of them with naming which doesn't make it easy to identify stuff. Plus the db files are changed (for Windows) when opening them. 
So now I don't know which the ones are with which I've been working at.
For immediate help: Could you explain the naming, so that I can identify files?
in the long run: I suggest to not produce backup files AND THEN open/work with them automatically, but instead I suggest making a backup, BUT have a different file name and ending like .db3_backup. and also never change the working file

**Comment by christofmuc** [comment] 2021-05-18 19:41
Öhm, let me think. The logic with the backup files is rather easy: 

Whenever you close KnobKraft, it will create a copy of the current database renamed to "-backup".

So if you open a backup file, it will create a -backup-backup, indicating this was created when investigating a backup. For your use case, you probably want to ignore all -backup-backups. 

The software currently has no concept of opening a database as "read-only", which is what I think you are suggesting regarding inspecting backup files. 

An easy way to work with the database files if something goes wrong is to just install a software like DB Browser (SQLite), which allows you to open the database and then search it if you can find the appropriate patch you're looking for.

**Comment by christofmuc** [comment] 2021-05-18 19:44
The timestamps can also be used to identify which database you might want to have a look at, and yes, it does create a new backup everytime you close the software :-/

Note that also if you want to archive the database content, you can also use the function export to PIF (Patch interchange format) - you can even export multiple databases into PIF files, and then create a new database loading all the PIF files and live with a merged database (in case that helps). 

The PIF files are JSON, so human readable, in a way.

**Comment by christofmuc** [comment] 2021-05-27 21:58
Suggested changes:

- If a filename contains "-backup", open the database in read only mode to not alter a backup. If you want to go back to use this, you can do the File... Save As.. command
- Show read only mode active in title bar
- Disable all buttons that would alter the database (well, at least the most obvious ones. Other functions will spit out a DATABASE ERROR log message
- Don't do a backup on closing of a backup - this causes irritation
- Could clean up disk space by deleting backups of backups? At least it could suggest to do so.

**Comment by markusschloesser** [comment] 2021-05-27 23:12
> Suggested changes:
> 
> * If a filename contains "-backup", open the database in read only mode to not alter a backup. If you want to go back to use this, you can do the File... Save As.. command
> * Show read only mode active in title bar
> * Disable all buttons that would alter the database (well, at least the most obvious ones. Other functions will spit out a DATABASE ERROR log message
> * Don't do a backup on closing of a backup - this causes irritation
> * Could clean up disk space by deleting backups of backups? At least it could suggest to do so.

All make sense, except for the last one, which, in my case would be deadly, since I obviously been unintentionally working with those files.

Thanks for your suggestion for DB Browser btw! I am now struggling with how to identify the correct patches. Is there a way to load all Andromeda db files, "join" them into one DB, leaving out duplicates but at the same time using presets which are tagged in favour of those which are not? Because it seems that I worked on multiple files from different states but all forks.

**Comment by christofmuc** [comment] 2021-06-06 23:03
> > * Could clean up disk space by deleting backups of backups? At least it could suggest to do so.
> 
> All make sense, except for the last one, which, in my case would be deadly, since I obviously been unintentionally working with those files.
Point taken!

> Thanks for your suggestion for DB Browser btw! I am now struggling with how to identify the correct patches. Is there a way to load all Andromeda db files, "join" them into one DB, leaving out duplicates but at the same time using presets which are tagged in favour of those which are not? Because it seems that I worked on multiple files from different states but all forks.

Sorry, saw this only now. I don't know how many files you think you worked in, but the merge is possible (also keeping the tags and user-decisions): Export each file into a PIF file (which is a JSON archive of the whole database), then create a blank new database and load the PIF files all into the new one via the "Load from computer" function. This will do the merge of the data as desired - not creating duplicates but retaining tags and favs. 

Should be possible as long as it's not more than 10 to 20 files, else you need more automation... I could probably make a helper program for that purpose, could come in handy at some point anyway.

**Comment by markusschloesser** [comment] 2021-06-07 10:18
Thanks! I currently have 92 db files for the Andromeda and 86 for the P12, so some kind of automation would be highly appreciated! (also shows that the current approach of when, how and how often to do backups can be "optimized" ;-), I am absolutely to blame for not looking into this earlier, but my usual approach is just "open the newest file" assuming all others can be ignored, which fucked things up)
I would have done this via db browser but am way over my head and no sql knowledge whatsoever

**Comment by christofmuc** [comment] 2021-06-07 10:55
@markusschloesser Ok, just to understand what happened - you went back to a database backup to find something, and then kept working in the backup?

Did you delete patches you are expecting to be in the old backup files?

What we can do is to make a "database merge tool" that loads all 92 database files and runs the merge logic - this will be a superset of all patches in all those databases (based on md5 sums). The manually given tags will be retained, just the patch names cannot be merged (if the same patch has two different names in two different databases, and it is not possible to figure out which one is "better"), so you'll end up with one of the names. 

Before I build a tool that is release ready, it is probably faster and more safe if you provide me with the databases? maybe zip them up and mail me a Google Drive link?

**Comment by christofmuc** [comment] 2021-06-12 13:33
@markusschloesser Ok... I did want to do something completely different, but then I ended up adding two functions to the 1.13.2 release that will be of help here:

  1. The File menu has a new entry called "Export multiple databases...", and when you click it it wants you to select a folder. Then it will iterate through all databases in that folder and create a .json file next to the database - this is a full json export of that database ready for import.
  2. The second entry is called "Merge multiple databases..." and really is a bulk import of all json files in the selected folder into the current database. So you could create a new blank empty database and then use the merge multiple... function to select the folder used in 1.), it will import all databases and deduplicate as usual. 

I tried to make it fairly stable and safe, and tried it here with 1900 database copies in my backup folder. It took a long time, but it worked. Let me know what you think!

BTW, you might have missed it but with 1.13.x I also finally released the Roland MKS-80.

**Comment by markusschloesser** [comment] 2021-06-13 13:57
Thanks so much! Already saw this reading the release notes.
Unfortunately currently swamped with work, so will have to take a look later. Will provide feedback

**Comment by markusschloesser** [comment] 2021-06-21 22:52
> 1. The File menu has a new entry called "Export multiple databases...", and when you click it it wants you to select a folder. Then it will iterate through all databases in that folder and create a .json file next to the database - this is a full json export of that database ready for import.

the "do not do something with files containing the words backup" has messed with the process, because the log file says:

`00:45:38: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda07.01.2021AllUser,AllPreset-backup.db3:attempt to write a readonly database
00:45:38: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda07.01.2021AllUser,AllPreset-backup2.db3:attempt to write a readonly database
00:45:38: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda07.01.2021AllUser,AllPreset.db3:attempt to write a readonly database
00:45:38: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED (schlo v1).db3:attempt to write a readonly database
00:45:38: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup.db3:attempt to write a readonly database
00:45:38: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup10.db3:attempt to write a readonly database
00:45:38: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup11.db3:attempt to write a readonly database
00:45:38: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup12.db3:attempt to write a readonly database
00:45:38: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup13.db3:attempt to write a readonly database
00:45:38: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup14.db3:attempt to write a readonly database
00:45:38: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup15.db3:attempt to write a readonly database
00:45:39: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup16.db3:attempt to write a readonly database
00:45:39: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup17.db3:attempt to write a readonly database
00:45:39: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup18.db3:attempt to write a readonly database
00:45:39: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup19.db3:attempt to write a readonly database
00:45:39: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup2.db3:attempt to write a readonly database
00:45:39: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup20.db3:attempt to write a readonly database
00:45:39: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup21.db3:attempt to write a readonly database
00:45:39: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup22.db3:attempt to write a readonly database
00:45:39: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup23.db3:attempt to write a readonly database
00:45:39: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup24.db3:attempt to write a readonly database
00:45:39: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup25.db3:attempt to write a readonly database
00:45:39: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup26.db3:attempt to write a readonly database
00:45:39: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup27.db3:attempt to write a readonly database
00:45:39: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup28.db3:attempt to write a readonly database
00:45:39: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup29.db3:attempt to write a readonly database
00:45:39: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup3.db3:attempt to write a readonly database
00:45:39: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup30.db3:attempt to write a readonly database
00:45:40: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup31.db3:attempt to write a readonly database
00:45:40: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup32.db3:attempt to write a readonly database
00:45:40: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup33.db3:attempt to write a readonly database
00:45:40: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup34.db3:attempt to write a readonly database
00:45:40: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup35.db3:attempt to write a readonly database
00:45:40: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup36.db3:attempt to write a readonly database
00:45:40: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup37.db3:attempt to write a readonly database
00:45:40: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup38.db3:attempt to write a readonly database
00:45:40: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup39.db3:attempt to write a readonly database
00:45:40: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup4.db3:attempt to write a readonly database
00:45:40: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup40.db3:attempt to write a readonly database
00:45:40: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup41.db3:attempt to write a readonly database
00:45:40: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup42.db3:attempt to write a readonly database
00:45:40: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup43.db3:attempt to write a readonly database
00:45:40: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup44.db3:attempt to write a readonly database
00:45:40: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup45.db3:attempt to write a readonly database
00:45:40: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup46.db3:attempt to write a readonly database
00:45:40: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup47.db3:attempt to write a readonly database
00:45:41: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup48.db3:attempt to write a readonly database
00:45:41: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup49.db3:attempt to write a readonly database
00:45:41: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup5.db3:attempt to write a readonly database
00:45:41: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup50.db3:attempt to write a readonly database
00:45:41: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup51.db3:attempt to write a readonly database
00:45:41: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup52.db3:attempt to write a readonly database
00:45:41: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup53.db3:attempt to write a readonly database
00:45:41: Exporting database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup54.db3 containing 1470 patches
00:45:48: Exporting database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup55.db3 containing 1470 patches
00:45:56: Exporting database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup56.db3 containing 1471 patches
00:46:03: Exporting database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup57-backup.db3 containing 1471 patches
00:46:10: Exporting database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup57-backup2.db3 containing 1471 patches
00:46:18: Exporting database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup57-backup3.db3 containing 1471 patches
00:46:25: Exporting database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup57-backup4.db3 containing 1471 patches
00:46:33: Exporting database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup57-backup5.db3 containing 1471 patches
00:46:40: Exporting database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup57-backup6.db3 containing 1471 patches
00:46:48: Exporting database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup57.db3 containing 1471 patches
00:46:55: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup6.db3:attempt to write a readonly database
00:46:55: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup7.db3:attempt to write a readonly database
00:46:55: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup8.db3:attempt to write a readonly database
00:46:55: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup9.db3:attempt to write a readonly database
00:46:55: Exporting database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-before-migration.db3 containing 1470 patches
00:47:03: Exporting database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-before-migration2.db3 containing 1470 patches
00:47:10: Exporting database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-before-migration3.db3 containing 1470 patches
00:47:18: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-before-reindexing.db3:attempt to write a readonly database
00:47:18: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-before-reindexing2.db3:attempt to write a readonly database
00:47:18: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-before-reindexing3.db3:attempt to write a readonly database
00:47:18: Error opening database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-before-reindexing4.db3:attempt to write a readonly database
00:47:18: Exporting database file M:\knobkraftMESS\Andromeda\AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED.db3 containing 1471 patches
00:47:25: Done, exported 75 databases to pip files for reimport and merge`

and there are/were 75 Andromeda db3 files but there are only 14 json files.
So, for that specific process, could you open the db files without writing to them?

**Comment by markusschloesser** [comment] 2021-06-21 22:52
or should I just temporarily rename the files and remove the words backup?

**Comment by markusschloesser** [comment] 2021-06-21 23:02
ok, used the new MS powertoys to rename. backup > bk_up. kk still doesn't want to open those files. What is kk looking for, when deciding if it's a backup files or not?

**Comment by markusschloesser** [comment] 2021-06-28 17:42
could I bother you with this again? https://github.com/christofmuc/KnobKraft-orm/issues/94#issuecomment-865394840 prevents me from cleaning up
@christofmuc

**Comment by christofmuc** [comment] 2021-06-29 16:53
@markusschloesser I'm in Denmark for 2 weeks, back next week, but what surprises me is that the result of your log file was "Done, exported 75 databases to pip files for reimport and merge", which seems about right and exactly what I expected. You can ignore the errors about the "attempt to write a readonly database" because it is handled by creating a temporary copy and then opening that copy in write mode (this is necessary for old databases that need migration before being exported). 

My expectation would be that there are 75 json files and not 14. Maybe the other files are incorrectly written to the temp directory, can you check that? Not sure which one it uses, maybe %TEMP%. There should be more json files somewhere... if you can't find them, I need to dig into the code and see why they are not written as expected.

**Comment by markusschloesser** [comment] 2021-07-02 23:16
have a nice holiday! :-)

> Maybe the other files are incorrectly written to the temp directory, can you check that? Not sure which one it uses, maybe %TEMP%. There should be more json files somewhere... if you can't find them, I need to dig into the code and see why they are not written as expected.

Unfortunately I couldn't find any additonal json files anywhere

**Comment by markusschloesser** [comment] 2021-07-07 22:33
@christofmuc sorry to bother you again with this, what is kk looking for, when deciding if it's a backup file or not?
Then I could just rename them accordingly

**Comment by christofmuc** [comment] 2021-07-12 21:51
@markusschloesser I try to understand what happened from the code.

The logic is as follows:

1. For the bulk import, it will always open the database as read only, because it does not want to create a new backup when closing it, and it does not want to accidentally write something to it.
2. If the database is old (old schema), it wants to upgrade the database schema to the latest version. This will fail, as it will try to write to the database in order to change the schema. The software is not able to use a database which has an old schema (would need the old version of KK for that). So the first error message about trying to write and that failing is expected. 
3. In case 2.) happened, it will copy the database into the tmp directory and open it in write-mode there, and then allow it to migrate to the new database schema (writing to the copy in tmp). The json file created however will be next to the original database. This process did not work as expected.

So it only exported the 14 out of 75 databases where step 3) was not necessary.

It might be something simple, but it is hard to spot like this - could you maybe provide me the "knobkraftMESS" folder as a zip privately e.g. on a Google Drive, then I can reproduce the error. If it is in the database migration code, all I need is one of the backup databases above where it did not export any patches for.

**Comment by markusschloesser** [comment] 2021-07-12 22:54
@christofmuc https://1drv.ms/u/s!Aqft2HaIMFnvgeckc44xo97pnc32pA?e=nh6W5V contains both folders P12 and A6. The "mess" (btw not talking about your mess, but mine! :-) ) happened with the Andromeda A6 folder, haven't tried other synths up till now.

**Comment by christofmuc** [comment] 2021-07-13 17:23
@markusschloesser Can confirm now there was a bug in the migration of old backups. This will be fixed with 1.13.3 - I have merged your stuff and shared via onedrive, you should have a mail on your GMX account. Please check and see if that has all you are looking for.

I have not yet enabled the readonly for Backups, as it keeps throwing tons of errors when you try to use the software, so the backup logic is still the same as it was, we just now have a way to resolve this mess ;-)

I'll close this ticket anyway now unless something new comes up.

**Closed by christofmuc** 2021-07-13 17:23 UTC
Labels: bug, enhancement

**Comment by christofmuc** [comment] 2021-07-14 10:54
Just published release 1.13.3 that should address the remaining issues of the export/merge process above. Note that merging a lot of databases will take a lot of time, e.g. it took over half an hour to merge the Andromeda databases.
