### ISSUE TITLE
clicking/assigning 2 categories crashes 

### ISSUE THREAD

**Issue by markusschloesser** [christofmuc/KnobKraft-orm#93] opened 2021-05-17 21:26 UTC
had a couple of crashes. Clicking 2 categories too fast after each other (when assigning a sound), reproducibly always leads to a crash.
Did you receive the automatic crash reports?

**Comment by markusschloesser** [comment] 2021-05-18 19:20
uh uh, lots of further crashes, searching for file name nearly always leads to a crash. Had 10 or so.
Also I seem to be missing a patch, is there a way to go thru all backups to find the missing one?

**Comment by christofmuc** [comment] 2021-05-18 19:46
Oh dear, you are using version 1.12.2? Sadly this was compiled without crash reporting, so there are no crash reports.

Searching for file name = searching for patch name? It seems you have a corrupt item in the database to cause that crash :-/ 

I can build a new version which has crash reporting turned back on.

**Comment by christofmuc** [comment] 2021-05-18 19:47
The bug you are descibing was fixed in 1.12.2, though. Maybe you're on 1.12.1?

**Comment by markusschloesser** [comment] 2021-05-18 19:50
Nope 1.12.2
Yes while searching for patch name. Might be because I am opening old db files?
Where are the crash dmps again? Can attach here manually

**Comment by christofmuc** [comment] 2021-05-18 19:54
Crash dumps should be in C:\Users\Christof\AppData\Roaming\KnobKraftOrm\sentry

**Comment by markusschloesser** [comment] 2021-05-18 21:29
unfortunately no, the reports folder only contains stuf from ages ago (Feb), will search SSD

**Comment by markusschloesser** [comment] 2021-05-18 21:29
> I can build a new version which has crash reporting turned back on.

might make sense to find out what's going on

**Comment by christofmuc** [comment] 2021-05-18 21:45
Please try version 1.12.3 - https://github.com/christofmuc/KnobKraft-orm/releases/tag/1.12.3
This is the same as 1.12.2 but crash reporting is enabled again!

**Comment by markusschloesser** [comment] 2021-05-18 21:52
thank you! :-)
Already installed and crashed it a couple of times. did you get the crash reports?
it seems to be the speed with which I type. Slowly typing is ok (same for categorization), but if I am too fast, kk crashes.

**Comment by christofmuc** [comment] 2021-05-18 21:57
Sigh, no crash dumps. I can see that you launch the software (there is an event sent on launch to test that the sentry is active), but the crashes do not seem to upload anything. I think we had the problem with your computer before. You can try the Help menu... crash the software... function to force a crash, that normally gets reported without any problems. 

I wonder if there could be any fireeall issues preventing the upload from working :-/

**Comment by christofmuc** [comment] 2021-05-18 21:59
Tested searching on my machine, and it always works, no matter how fast I hammer the keys. Can you try in a new database to make sure it is not some database content?

**Comment by markusschloesser** [comment] 2021-05-18 21:59
> Sigh, no crash dumps. I can see that you launch the software (there is an event sent on launch to test that the sentry is active), but the crashes do not seem to upload anything. I think we had the problem with your computer before. You can try the Help menu... crash the software... function to force a crash, that normally gets reported without any problems.

just forced crashed

> I wonder if there could be any fireeall issues preventing the upload from working :-/

no fw for outgoing stuff (except smb)

**Comment by markusschloesser** [comment] 2021-05-18 22:01
> Tested searching on my machine, and it always works, no matter how fast I hammer the keys. Can you try in a new database to make sure it is not some database content?

i could send the db files?
[AlesisAndromeda08.01.2021AllUser,AllPreset, ALL OTHER IMPORTED-backup57-backup6-backup2-backup.db3.zip](https://github.com/christofmuc/KnobKraft-orm/files/6504638/AlesisAndromeda08.01.2021AllUser.AllPreset.ALL.OTHER.IMPORTED-backup57-backup6-backup2-backup.db3.zip)

**Comment by christofmuc** [comment] 2021-05-18 22:04
Ok, interesting, the force crash worked. So it is the way the software crashes that leads to no crash dump being generated. This is usually the case when it dies somewhere in the Python code. I'll look at the database now!

**Comment by christofmuc** [comment] 2021-05-18 22:07
Good news - I can reproduce it with the database, it crashes somewhere in the calculateFingerprint function. Now will investigate why...

**Comment by christofmuc** [comment] 2021-05-18 22:47
Phew, that's a tough one. Can confirm it is easily reproducible with fast typing or deleting, but the crashes look like some weird mult-threading problem where the root cause is not obvious. I did not see any corrupted data, but lots of crahes in the python calling code where it should not crash. This will take a bit longer.

**Comment by markusschloesser** [comment] 2021-05-18 23:10
ok, sorry about that! :-)
don't know if that's relevant, but the actual db files are not local, but on a network drive (NAS/Server). But even when those disks are spun down it never crashed, might just take a while longer to open and close.

**Comment by christofmuc** [comment] 2021-05-27 21:41
Ok, this was a tough cookie based on multithreading into the database and having too many threads going into Python (the reason this happened now was that the Andromeda A6 adaptation now has a calculateFingerprint() method, which is used a lot during those queries). Found it and hopefully fixed it, will be part of the next release. I want to test a bit more before It trust my changes here.

**Comment by markusschloesser** [comment] 2021-05-27 23:13
I am glad that it wasn't my fault 😇😂 and sorry to hear about the effort (and of course grateful for it!)

**Comment by christofmuc** [comment] 2021-06-06 22:41
Bugfix released with 1.13.0

**Closed by christofmuc** 2021-06-06 22:41 UTC
Labels: bug
