### ISSUE TITLE
Crash during multiple bank import from synth

### ISSUE THREAD

**Issue by GriffReborn** [christofmuc/KnobKraft-orm#16] opened 2020-10-11 10:38 UTC
Importing from synth fails if you import more than one bank at a time, it hangs at 99% after the first bank.  This happens if selecting more than one bank, or using import all button.

Importing individual banks works more reliably, but still occasionally hangs at 99%.  If you cancel the import, the data is not there, if  you start the import again, the app crashes and closes.

Windows 10 1903 - 18362.1082
MOTU MIDI Express XT with latest drivers.
Virus OS 4.9

**Comment by christofmuc** [comment] 2020-10-11 11:38
Thank you for the bug report! I have seen the same behavior with my Virus B, but not frequently. I suspect in case a MIDI message goes missing, the app is still waiting like for patch #99 and doesn't accept that the patches are done.

I am using the same MIDI Interface, so that might point me in the right direction.

Certainly there is also another problem in that canceling the download and restarting shouldn't crash, I will look into it!

Again, thank you for reporting!

**Comment by GriffReborn** [comment] 2020-10-11 12:04
Changed issue description, as I've just had the same thing happen importing from Rev2.

**Comment by GriffReborn** [comment] 2020-10-11 12:18
Just happened when importing a single bank from Rev2:

Faulting application name: KnobKraftOrm.exe, version: 0.0.0.0, time stamp: 0x5f818afd
Faulting module name: ntdll.dll, version: 10.0.18362.1049, time stamp: 0xb5beef21
Exception code: 0xc0000005
Fault offset: 0x00000000000072a6
Faulting process ID: 0x278
Faulting application start time: 0x01d69fc69089692b
Faulting application path: C:\Users\**REDACTED**
![KnobKraftOrm_6p8TzBoAAF](https://user-images.githubusercontent.com/11091780/95678373-2d833080-0bc4-11eb-8c25-70a6ff085d1c.png)
\AppData\Local\Programs\KnobKraftOrm\KnobKraftOrm.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report ID: c4873a8b-6bfa-4b0d-8e10-4e5a924b147a
Faulting package full name: 
Faulting package-relative application ID:

**Comment by christofmuc** [comment] 2020-10-11 12:37
Is you Rev2 connected via the MIDI Express XT or directly via USB?

**Comment by GriffReborn** [comment] 2020-10-11 12:51
Rev2 is on the XT.  Can't get it to work over USB, I get message "Failed to open MIDI device Rev2, maybe it's turned off or used by another software?".

**Comment by christofmuc** [comment] 2020-10-11 12:59
This suggests that multi-client MIDI is not there yet with Windows USB devices, unless they use the new API (which I think JUCE as a framework doesn't): https://www.gearslutz.com/board/music-computers/1214965-microsofts-native-midi-driver.html

Do you have a DAW or MIDI OX open which could block access to the USB for the Orm?

**Comment by GriffReborn** [comment] 2020-10-11 13:21
No, no other MIDI apps open.  And I set everything in GLOBAL from MIDI to USB.

**Comment by christofmuc** [comment] 2020-10-19 21:33
> 
> 
> Rev2 is on the XT. Can't get it to work over USB, I get message "Failed to open MIDI device Rev2, maybe it's turned off or used by another software?".

That might be another bug, for me USB works out of the box as expected.

**Comment by christofmuc** [comment] 2020-10-19 21:36
Closing this, as release 1.7.3 contains multiple stability bug fixes. Those were around cancel-behavior, however. The reason the download gets stuck is unclear to me, the crashes I could reproduce e.g. by switching off the MidiExpress in the middle of a download were due to cleanup problems after cancel. I have yet to see it crash during a normal download.

What I have seen is that most synths don't like it very much when other MIDI messages are sent while a bigger sysex transfer is under way, e.g. keep playing while the download happens. And if a single message goes missing, the bank dump will not complete because it will simply count the patch messages and wait until it got enough.

**Closed by christofmuc** 2020-10-19 21:36 UTC
Labels: bug

**Comment by christofmuc** [comment] 2020-12-17 14:49
I added a new issue for the Rev2 problem - need to test it again after I changed a lot in the USB code: 
#30 

The Virus hanging at least was also reported now for the Virus C, so I opened a fresh ticket for that:
#31 

The crashes should be fixed by now, I have not seen any new crashes in that area.
