### ISSUE TITLE
Publishing ORM databases

### ISSUE THREAD

**Issue by Mostelin** [christofmuc/KnobKraft-orm#170] opened 2022-07-29 20:47 UTC
When I have finally ironed out all the little issues with getting my database of Ensoniq sounds into the ORM, I will move onto the next step in my project, which is to re-publish the collection to the Ensoniq community. Most of these programs have circulated on the internet for years, with much dispersion, disorganisation, duplication, file corruption, and lost layering. It is my goal to bring them all together and banish these problems once and for all.

I will be publishing the collection in .syx form, for those who want it, but this amounts to 145 bank files (each of 40 programs), and 5,762 single-program files, and that still represents quite a look-up challenge to any user who is after a particular sound and timbre.

So publishing them in parallel in ORM form seems like a very good idea. From my investigation of the structure of the db3 database, it looks self-contained. In other words, the single file can be shared, and any recipients only have to download the ORM to open the db3 file, and should have:

- the Ensoniq adaptation already set up (though they will need to tie this to their own MIDI setup)
- the same tagging/categorisation as I have set up
- data to link each program to its original .syx bank filename and its position
- the ability to further tag/categorise programs and create their own lists

So, all I need to know is whether the above is correct, or whether some other file(s) or set-up would also be required?

And lastly, would you mind if I pointed the Ensoniq community to the ORM? This will probably generate a wave of demand for user support.

**Comment by christofmuc** [comment] 2022-07-29 21:45
@Mostelin Exciting!

Good question how to distribute! Distributing the single SQL file certainly is the easiest way, as I keep updating the database format always with migration scripts. So yes, if you distribute the SQL file, anybody with an ORM should be able to open them. Sqlite files are by design cross platform, so you need only one file.

In the database there are already the correct categories and the original import information. What is missing is the to turn on the ESQ in the synth setup, but that is probably a no-brainer as a freshly installed Orm will open up with a page to select a synth.

If we want to retain the data for the future (archival), the PIF format is better because it is kind of human readable and everybody figuring out the base64 encoding of the sysex will be able to harvest the data in there.

The very first version of the Orm btw didn't use Sqlite but stored the patches in the Internet in an AWS database... in the end it was too inflexible and slow to develop, but now with the patch tree on the left hand side we could also think of reactivating the community/web storage... this way, everybody would rather "mount" the web archive and copy from there, The code is currently disable though and my focus this summer is to finally get the bank management done, the single most requested feature.

And please, point people to the Orm. It is a hobby project still, but I love users and like to see the software in action!

**Comment by Mostelin** [comment] 2022-07-31 08:12
@christofmuc 
Once again, I am really glad you are so helpful with this.

In the next day or so I will be publishing the database. The documentation for it now makes a few references to the ORM, which I hope are not misleading. I've attached the document here. Sections 1 and 7 refer to the ORM. If you have the time and inclination, could you check what I say about its features and how to get started with it?

[Ensoniq Programs.zip](https://github.com/christofmuc/KnobKraft-orm/files/9228352/Ensoniq.Programs.zip)

**Comment by christofmuc** [comment] 2022-08-01 19:35
@Mostelin Awesome work! You will be forever hailed by the followers of the Great Ensoniq! I added three small comments to the document, only cosmetic, hope you can see the comments I made with Acrobat:

[Ensoniq Programs.pdf](https://github.com/christofmuc/KnobKraft-orm/files/9236810/Ensoniq.Programs.pdf)

Really impressive, too bad I don't own an SQ-80 :-)

One thing I was thinking - is the parameter list surely known, i.e. you know which bits in the sysex are which parameter? The Orm can display the parameters (currently in the diff dialog) for synths that provide this info. Again as of now only in the C++ code, but should be easy to expose to Python, too.

Not only would you get a display of the paramters in the diff dialog, but there is a hidden search function where you can then search for patches which have specific paramter values. E.g. I used it to search for patches that make use of the slightly arcance Prophet Rev 2's "audiomod" feature, to see what people do with it. I put it into #51, but never really finished it. Could become also a problem in terms of performance, but it is a very special feature that I have seen nowhere else...

**Comment by markusschloesser** [comment] 2022-08-01 22:36
> too bad I don't own an SQ-80 :-)

if you have a Windows PC you can use SQ8L (http://www.buchty.net/ensoniq/ ), which works great with knobkraft. But as it is a vst2 32bit, you need to additionally use DDMF's metaplugin, to wrap it into something usable with a 64bit host.

**Comment by Mostelin** [comment] 2022-08-02 00:31
@christofmuc 
Thank you for the feedback. I've made all the changes you suggest and re-uploaded.

As for the parameters...

Yes, they are known. In my own database I created a form that does the decoding of bytes and displays the value of each parameter under its label. At times I've found this useful for analysis, but I never took the step of making it prescriptive as well as descriptive. In other words, there are no safety rails to prevent out-of-range data entry.

Your idea intrigues me. Are you thinking in terms of read-only?

**Comment by christofmuc** [comment] 2022-08-21 20:39
> As for the parameters...
> 
> Yes, they are known. In my own database I created a form that does the decoding of bytes and displays the value of each parameter under its label. At times I've found this useful for analysis, but I never took the step of making it prescriptive as well as descriptive. In other words, there are no safety rails to prevent out-of-range data entry.
> 
> Your idea intrigues me. Are you thinking in terms of read-only?
Yes, what the C++ code can do right now is to decode the parameters in a synth and display them, also in the patch comparison mode. This is what it looks like in patch compare for the DW 8000:

![grafik](https://user-images.githubusercontent.com/5006524/185809996-4c859e9d-d8b7-4e1a-a8d4-95d51ca7b6d7.png)

**Comment by Mostelin** [comment] 2022-08-22 18:01
Much of the work is done. The image below is from my database. On the left-hand side you can see the raw Ensoniq program data as it is encoded in bytes (Program Data) and the actual nybbles within this that contain parameter information (ShortData). Bits-to-integer extraction produces the >100 integer parameters on the right-hand side. Could you feasibly accommodate this many parameters in the user interface?

The remaining work for me would be compiling lookup lists to further translate all the WAVE and MOD integer parameters to their recognised names (SAW, PIANO1, NOISE3, etc, and WHEEL, LFO1, OSC2, etc). Some parameters should also probably be flagged as needing to be translated from 0 and 1 to 'off' and 'on'. Finally, there are some oddities such as 'if parameter 2R = 1, then parameter T4 = T4 + "R". I don't mind doing this, but such lists, flags and arbitrary rules would have to be handled in your code. Or, I guess, we just settle for integer parameters instead.

Maybe this is something to think about after you have bank management working nicely?

![EnsoniqProgData](https://user-images.githubusercontent.com/95011279/185980323-e2278f61-e24b-4868-bbfa-00d7ff6f76a5.png)

**Comment by christofmuc** [comment] 2022-08-22 21:02
@Mostelin Nice! Yes, and if those parameter mappings also come with the data for a single param update command sysex, it opens the gate to implement SW editors for those synths. But then we're in CTRLR and Electra One territory. The Orm contains code that makes automatic BCR 2000 controller setups based on these settings, including bidrectional patch linking so e..g on my Matrix 1000 I switch a patch and the BCR's LED rings show the current values. There is a lot that can be done, but yes, keeps distracting from the next major milestone :-)

**Comment by christofmuc** [comment] 2023-01-08 15:04
Closing the ticket about the database publishing question, have created #199 to track the parameter extraction feature.

**Closed by christofmuc** 2023-01-08 15:04 UTC
Labels: question
