### ISSUE TITLE
2.0.1 crash and inconsistent display of bank names

### ISSUE THREAD

**Issue by bboc** [christofmuc/KnobKraft-orm#226] opened 2023-02-16 22:13 UTC
I found a couple of things I can't explain:

When I remove friendlyBankName() from an adaptation and reload the python file, the app crashes when I select that device in the tree. Only when I add the `friendlyBankName()` again the app can access that part of the tree again. other devices work fine. 

The [Programming Guide](https://github.com/christofmuc/KnobKraft-orm/blob/master/adaptions/Adaptation%20Programming%20Guide.md) claims that the output of `friendlyBankName()` "_is displayed whereever a patch location is shown in the Orm_.". However, that is not the case:

![image](https://user-images.githubusercontent.com/520442/219496047-c510f566-b6b6-46e1-92c4-b53822eca853.png)

In this picture you can see 3 different places where the bank number should be displayed, and you see three variants of bank number display:

- the tree uses the output of `friendlyBankName()` (in this case "A", as "Bank" is hardcoded into Knobkraft here)
- the grid uses the output of `friendlyPatchName()` (which in this case only returns the input value for debugging)
- the bank panel (at the top where it says "Bank 'Bank A'") uses the output of `bankDescriptors()`

This can be fixed in the adaptation, of course, but the app should not crash, the documentation should mention all that explicitly.

**Comment by christofmuc** [comment] 2023-02-18 15:05
I could not reproduce the crash on my Windows machine, must try again on macOS. 

Regarding the bank names:

1. The logic should be the bankDescriptors() always takes precedence over friendlyBankName(). In your picture I see "Bank A" on the left in the tree which seems correct and I could not find out where Bank is hardcoded there. On the right in the bank display there is a text "Bank .." which has a hardcoded bank in it, which is why we have Bank 'Bank A'... So we could remove Bank From that text. I don't see an inconsistency here, and couldn't find one in the code.
2. The patch buttons are indeed labeled with the output of friendyProgramName. In my implementations, that always includes the bank as well if I can determine it (not in all synths that is the case). So I woud implement friendlyProgramName with the help of friendlyBankName to get this in Sync?

**Comment by bboc** [comment] 2023-02-18 19:30
I uninstalled the app completely and reinstalled 2.0.1. Now it looks like everything works as it should.

I think the "problem" here is that bankDescriptors() doesn't have enough information to derive the friendlyProgramNumber(), because it doesn't store the offset for the first program (numbers in banks can start with 1, as in the AS-1, or with 0, as in the Modor NF-1), and it doesn't store a format string. So friendlyProgramName() is still required, and that inevitably implies writing the code that currently sits in friendlyBankName().

To keep this free of redundant code, I now implemented both friendlyProgramName() and bankDescriptors() using  friendlyBankName(). But if bankDescriptors() stored firstIndex and lastIndex, and a format string, both friendlyProgramName() and friendlyBankName() might not be required except for very special cases.

**Comment by christofmuc** [comment] 2023-02-19 12:35
Interesting idea! Maybe we should look at this when doing the #220. There is no common format string format, Python format might format differently than C++, so we'd anyway need to callback into Python to format the bank descriptor's string - and friendlyProgramName already provides a method for that. 

I tried to make the Python interface as simple (and stable) as possible, even if that means having a bit repeat or stupid functions. That comes biting back now with the number of roundtrips becoming a real performance problem.

**Comment by christofmuc** [comment] 2023-02-19 12:40
I removed the hardcoded 'Bank ' text in the Bank Panel for the next release, seems wasteful screen resource usage. Closing this, keeping the reference within #220.

**Closed by christofmuc** 2023-02-19 12:40 UTC
Labels: bug, need more information
