### ISSUE TITLE
2.0.0 Inexplicable colour changes in log window

### ISSUE THREAD

**Issue by Mostelin** [christofmuc/KnobKraft-orm#214] opened 2023-01-16 12:21 UTC
At first it looked like there is now a standard colour code for messages in the log:
- white for info
- blue for warning
- red for error

However, after doing a bank import (which may or may not be relevant) I noticed that some info messages were blue, and then they all became black - nearly illegible against the dark grey background.
![Capture](https://user-images.githubusercontent.com/95011279/212676848-4cda65e5-0ce5-428a-b38f-6cad294254df.PNG)

**Comment by christofmuc** [comment] 2023-01-17 22:16
Confirmed, there is more than one bug in the output window. I need to look at that again.

**Comment by bboc** [comment] 2023-02-14 21:08
I have that same issue, it looks like the text is black at first, and it starts colouring the log real slow. With a lot of log output, e.g. when testing an adaptation, the tail of the log is never readable. In addition to that, clean log does not work, the log is not truncated.

**Comment by christofmuc** [comment] 2023-02-14 22:13
Ok, I'll turn the colours off for the next release, I think the UI component might not be suited for a large amount of colour changes. @bbox After I turned it off, I could not reproduce your problem with clear, for me it always clears the log. Anything special you're doing or logging?

**Comment by christofmuc** [comment] 2023-02-15 22:44
Fixed with release 2.0.1

**Closed by christofmuc** 2023-02-15 22:44 UTC
Labels: bug
