### ISSUE TITLE
Privacy Concern - Using Microphone

### ISSUE THREAD

**Issue by GriffReborn** [christofmuc/KnobKraft-orm#15] opened 2020-10-11 10:33 UTC
Windows Defender and BitDefender both report the app is using the microphone.

**Comment by christofmuc** [comment] 2020-10-11 11:36
Ups, that certainly shouldn't be the case! I know the JUCE library contains an Audio Device Manager, and that might open the first Audio device it finds on intialization, as this is not an Audio app but rather only MIDI, I have not really looked into the init code, maybe I can turn it off completely or at least make it visible to the user which Audio device is selected, should JUCE really insist on one. 

How does Windows Defender report that, so I can reproduce? I have Windows Defender, but I never saw it reporting this kind of problem? 

Thank you for notifying me!

**Comment by GriffReborn** [comment] 2020-10-11 12:02
Actually, I'm made an assumption that it's Defender, as in the first case, it was BitDefender on my other PC which reported it.  It just appears in the systray.

![wbrkANpR3H](https://user-images.githubusercontent.com/11091780/95678079-0c214500-0bc2-11eb-9fa6-297f9eaffcb1.png)

**Comment by christofmuc** [comment] 2020-10-11 12:15
True, I was able to reproduce it once, and then Windows stops complaining. It does cache somehow that it already notified me, in a registry directory that is part of Internet Explorer...

Computer\HKEY_USERS\S-1-5-21-1172384583-1437106714-3961794235-1001\SOFTWARE\Microsoft\Internet Explorer\LowRegistry\Audio\PolicyConfig\PropertyStore\1c90a391_0

It also does store the history of the accesses in this directory, deleting these does remove the entries from the "desktop apps that accessed your microphone" history list, but does not bring back the warning on the next launch:

Computer\HKEY_USERS\S-1-5-21-1172384583-1437106714-3961794235-1001\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\microphone\

There is more entries here, but that does not seem to influence the warning either:

Computer\HKEY_USERS\S-1-5-21-1172384583-1437106714-3961794235-1001\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FeatureUsage\AppSwitched

I think the reason that it comes up is that I instantiate the JUCE AudioDeviceManager - actually for a good reason, as there is a feature currently disabled in the release that I am working on that will allow you to generate "thumbnails" of all patches on the synth and render the waveform on the button, especially useful for synths that have no names for patches because they are early 80s.

So even if the software never opens an audio device, Windows suggests it uses your "microphone", suggest any audio input. 

I have sadly no idea how to bring the warning back on my machine so I could experiment on how to setup the software so the warning is issued only when the app *really* is going to use an AudioIn device, but so far this is very non-reproducable.

**Comment by christofmuc** [comment] 2020-10-11 12:25
Ok, its getting clearer now - I cannot for the life of me bring back the warning the Windows Defender showed once, but when I allow Microphone access to Desktop Apps and launch The Orm, the Microphone Tray icon is shown. That is correct, but confusing because the feature using the audio in port is not enabled in the UI.

But actually the disabling in the UI does not disable the audio device from being opened. Nothing happens with the data, but you're completely correct that this should not happen without the feature being visibly enabled. I'll disable the instantiation completely until the feature is ready for release! 

Thank you!

**Comment by christofmuc** [comment] 2020-10-19 21:17
This was fixed with releaese 1.7.3, thanks again for reporting!

**Closed by christofmuc** 2020-10-19 21:17 UTC
Labels: bug
